version: '3.8'

services:
  bot:
    build: .
    container_name: my-telegram-bot
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"