version: '3.8'

services:
  bot:
    build: .
    container_name: my-telegram-bot
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      - bot_runtime:/app/.runtime
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    restart: always

volumes:
  bot_runtime:
