name: Deploy Bot to Server

on:
  push:
    branches:
      - main  # Деплой будет срабатывать при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e  # Прекращать работу при любой ошибке
            
            PROJECT_DIR=~/bot-folder
            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR

            # 2. Обновляем код из репозитория
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git fetch --all
              git reset --hard origin/main
            fi

            # 3. Обновляем переменные окружения
            echo "${{ secrets.ENV_FILE }}" > .env

            # 4. Пересобираем и запускаем
            # --force-recreate гарантирует, что контейнер будет обновлен из нового образа
            docker-compose up -d --build --force-recreate

            # 5. Очистка старых (висячих) образов
            docker image prune -f